// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP4oOwkXLnyLd79sSGmv4hSyHi2vav04g',
    appId: '1:319306802968:web:dc015273dc630cf951206d',
    messagingSenderId: '319306802968',
    projectId: 'to-do-app-5ec33',
    authDomain: 'to-do-app-5ec33.firebaseapp.com',
    storageBucket: 'to-do-app-5ec33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3SVMhjlPaz-Oan9rjFXqwE6pbIdBttIU',
    appId: '1:319306802968:android:8e3657e88d24d00351206d',
    messagingSenderId: '319306802968',
    projectId: 'to-do-app-5ec33',
    storageBucket: 'to-do-app-5ec33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4gWgfodxGdiV7oP572Uz3wIPCgjI7IF4',
    appId: '1:319306802968:ios:4964c3851a1e95eb51206d',
    messagingSenderId: '319306802968',
    projectId: 'to-do-app-5ec33',
    storageBucket: 'to-do-app-5ec33.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4gWgfodxGdiV7oP572Uz3wIPCgjI7IF4',
    appId: '1:319306802968:ios:4964c3851a1e95eb51206d',
    messagingSenderId: '319306802968',
    projectId: 'to-do-app-5ec33',
    storageBucket: 'to-do-app-5ec33.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP4oOwkXLnyLd79sSGmv4hSyHi2vav04g',
    appId: '1:319306802968:web:dc015273dc630cf951206d',
    messagingSenderId: '319306802968',
    projectId: 'to-do-app-5ec33',
    authDomain: 'to-do-app-5ec33.firebaseapp.com',
    storageBucket: 'to-do-app-5ec33.firebasestorage.app',
  );
}
